source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
# Uncomment this line if you're using Swift
use_frameworks!

inhibit_all_warnings!

def pods_lib
 pod 'Moya', '~> 14.0'
end

target 'DemoProject' do
    pods_lib
end

target 'DemoProjectTests' do
end

target 'DemoProjectUITests' do
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
								config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
								config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end